---
- include: locale.yml
  tags:
    - locale

- include: os_packages.yml
  tags:
    - packages

- include: network.yml
  tags:
    - network

- include: filesystem.yml
  tags:
    - filesystem

- include: user.yml
  tags:
    - user
