- name: add label to existing namespace
  kubernetes.core.k8s:
    state: present
    kind: Node
    name: ansible_hostname
    definition:
      metadata:
        labels:
          node.longhorn.io/create-default-disk: "true"
  delegate_to: localhost