- name: Create directory for label for nfd
  file:
    path: /etc/kubernetes/node-feature-discovery/features.d/
    state: directory

- name: add label for nfd
  copy:
    dest: /etc/kubernetes/node-feature-discovery/features.d/my-features
    content: "longhorn-node=true"