---
- hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: Ubuntu upgrade
      ansible.builtin.apt:
        upgrade: full
        update_cache: true
        cache_valid_time: 3600
        autoclean: true
        autoremove: true
      register: apt_upgrade
      retries: 5
      until: apt_upgrade is success
      when: ansible_facts["distribution"] == "Ubuntu"

    - name: Fedora upgrade
      ansible.builtin.dnf:
        update_cache: yes
        name: '*'
        state: latest
      when: ansible_facts["distribution"] == "Fedora"
