apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: observability
stringData:
    admin-user: ENC[AES256_GCM,data:Ib41wes=,iv:F5cOevQ2srG6SKWlv1v67Tanra25tKVoEMvhQW1kOEw=,tag:Y8kCkoRjwO/lYLEJtGUCag==,type:str]
    admin-password: ENC[AES256_GCM,data:n4G6NUXpAPBiWcgXn/70pJu2Owd2J+T+kSaY39IdEO0=,iv:YkxoKj7RsPXKTQpCPOA+//KGgUl4DQ/uhuSlEP4dRX0=,tag:W/3aE4XhN0iFoHu0F4olgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvb0VOTSswbWFkVnZDc1R3
            cFpqMmxtM3pQRG0wTndidG5lVHhIMzRaeHdNCmMxSlZubU5rVWNKaTd1TFpQT0Fk
            c1psNFV4aUlhYktoVnVEMU13SEJ3clUKLS0tIG1zejE4R2g4S09FZTVyazlEa0ZP
            cG0yakdUd2g1U0F6dFpxWjlQWDFmODAKffpvyLP1QwHnbxno4xGxv427G8zkf4vO
            6FsvZuT7btIGhJrlejevHyqVk5CpWLUJwh5/FJaX7/jeybrOMmO1Mw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16vs9crdp7cxwjtlqu5l83a3pgdah9eau3afrhx7qyzkhag7avq0spf6rxp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T21:56:39Z"
    mac: ENC[AES256_GCM,data:xUdzxXpmeTk3ykGKnUb4bV3H5c4dybGNlEk0GoH9fAs7Xh8O7Rv1Wa7fPlb06K/e2e+a64AYS4hGg+olV5jpZPjnaWDLo+N+ujdNmzmFnXBRvUKlRypRGYdvRPkuqb6gUzaB2HWz7FyXp3Y6/taZiC+/s/2gUI0ILBzowIRmKN4=,iv:bCsZf08uMkoCuOMpRaSb3L4VcM/Z4ZJrQD2mXEwAxLg=,tag:ntzgLVs6sdJ2+hiVUD0VNA==,type:str]
    version: 3.13.0
