---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app tautulli
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/tautulli
      tag: 2.10.4
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: 8181
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          external-dns.home.arpa/enabled: "true"
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: &host "{{ .Release.Name }}.k8s.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: tautulli-tls
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        existingClaim: *app
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 500Mi
