---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-config
  namespace: default
  labels:
    app.kubernetes.io/name: vikunja
    app.kubernetes.io/instance: vikunja
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
