apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
    namespace: default
stringData:
    VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:HahOHveVIhZ12msAKUpmtcRSY5QzLg6uPBBSwsMcefqzWmKNpHmrqEK9T2Q2S6hRRGQ20d1GCx/ZVegc3oXpwg==,iv:j4vTD0BeYPiZfaiIoZ71mxoiKhK1+ypVtzyFG6pn0yU=,tag:0nB5xrGU5khIPEltXqWViw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcWc1cXIyNlB3ampGbWRm
            Q3Z1K0ROcEU5ZVlHblM3dG5TYWQ5V0EvQ3lVCnd2eVpHdWhIeUZzZE9IUDNjV0ZH
            YWVMeGZadkpNTlFqMm1YU2NMaVpTWU0KLS0tIGkyV3poT2wvTmZHSnIvT3l3TWMr
            S1FGSEp6MHdKZ0l6RkNIc1FxQ1BudG8Kz6Vie300iXRekEdVPUqVX4oVN8NefL2T
            A5IVLX2ZsOfiPD2IRJnh392LuA45sfg9m6d3DweOVvwB83bnrnhH1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16vs9crdp7cxwjtlqu5l83a3pgdah9eau3afrhx7qyzkhag7avq0spf6rxp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T05:12:33Z"
    mac: ENC[AES256_GCM,data:0c8fh3k+Wj2aGka+XgDtVHYmDEDm00GUtHORS1tQrfZDWSjAXyeZ+v5pqXoUvdu81CFvwikpoSUlsfEVVcYgFALSm5wZVe9avCopvzmOKAI9h8YYVh4fk4WlCr91nN+Y2E7QnzeKs3DNwwwnFMh+zsyEgCX8GHGDji05uP0zI0I=,iv:++KPWFPUBo/Gx7tZiDbiTvBZv34LGrK7UjtJGQkOYEs=,tag:v2E1eA0yr59cJxRKd6hL0w==,type:str]
    version: 3.13.0
