apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces
  - longhorn-system
  - cert-manager
  - kube-system
  - metallb-system
  - system-upgrade
  - node-feature-discovery
