---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app radarr
  namespace: media
spec:
  dependsOn:
  - name: longhorn
    namespace: longhorn-system
  - name: traefik
    namespace: networking
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/radarr
      tag: 4.2.4.6635
    env:
      TZ: "${TIMEZONE}"
      RADARR__INSTANCE_NAME: Radarr
      RADARR__LOG_LEVEL: info
      RADARR__APPLICATION_URL: "https://movies.k8s.${SECRET_DOMAIN}"
      RADARR__PORT: &port 80
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/enable: "true"
          hajimari.io/icon: movie-roll
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: &host "movies.k8s.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: radarr-tls
    persistence:
      config:
        enabled: true
        existingClaim: *app
      nas-nfs-media:
        enabled: true
        type: nfs
        server: "nas.${SECRET_DOMAIN}"
        path: /mnt/storage-x/media/plex/Movies
        mountPath: /movies
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
