---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 16.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/onedr0p/radarr
      tag: "4.2.4.6635"
    env:
      TZ:  "${TIMEZONE}"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "movie-roll"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          # kubernetes.io/ingress.class: "nginx"
          # external-dns.alpha.kubernetes.io/target: "home.${SECRET_PUBLIC_DOMAIN}"
          # nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_PUBLIC_DOMAIN}/oauth2/auth"
          # nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_PUBLIC_DOMAIN}/oauth2/start
        hosts:
          - host: "movies.k8s.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "movies.k8s.${SECRET_DOMAIN}"
            secretName: "radarr-tls"
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config-pvc
      nas-nfs-media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "nas.${SECRET_DOMAIN}"
            path: /mnt/storage-x/media/plex/Movies
        mountPath: /movies
        readOnly: false
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
