---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 172.16.50.200-172.16.50.240
  METALLB_TRAEFIK_ADDR: 172.16.50.200
  METALLB_LB_GTWY: 172.16.50.1
  TIMEZONE: America/Chicago
