---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 172.16.50.100-172.16.50.150
  METALLB_TRAEFIK_ADDR: 172.16.50.100
  METALLB_LB_GTWY: 172.16.50.1

