apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: &name plex-media-manager
  namespace: media
  labels:
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  storageClassName: longhorn