apiVersion: v1
kind: Secret
metadata:
    name: sonarr
    namespace: media
type: Opaque
stringData:
    SONARR__API_KEY: ENC[AES256_GCM,data:aRrJ/mtLRmVkq0NGMXZF2M+fjCMfUNuFP7ucmyAQTHo4zgBufzrhkWcQJ9M=,iv:M2LUgCMQobA6kHZcz3XyobqgARKnp07VaCvFLcjXDQ4=,tag:CRRs22pY6xN7tHkSUhbetA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vs9crdp7cxwjtlqu5l83a3pgdah9eau3afrhx7qyzkhag7avq0spf6rxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bkpjTWs2SG5nZHBPeUt5
            M212OUt1VkdGV0R6dW93Smx1aklJRVNJQW1ZCitDM0tSRnIzeUd5bXRRd0JFMW10
            alpiVlVPbDlPd1dNdmJlTWowTytWUEUKLS0tIFRSVGlEQjFNQjBKRWNkcHRuMita
            MXNCeVkzc2ZzUm1paUlSby9KMWsxYnMKhi5UvgyUrYBYsLuyW54chU2AyLQYKIc+
            x4CppJnTwF/bL8TY4nm/Nm2SXJnb71IJKx79DGasVw75+2sLif6+/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-11T02:32:26Z"
    mac: ENC[AES256_GCM,data:u/LhIOJlLCcSMriv6tZ95CNGtrDp5x2GqFaFy7r4Jf94SyE+t3JUCq5RStokicAu37mYK9aqQQkyKZJ3Jl4bOb3d1j2d0m7HCIUXO77Rn9I4KPDb1/SZzsqXSH9F8QjdXq3Wnbm3AizjsMgs6bhmDvUMZ4eBQMt2V23tOObiiNw=,iv:J5hG+SmN9usZArlPgDLTAZWhkGcmcTTh835jYYg2GkM=,tag:SKOtcY0CCwIh71pOXFhqyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
