---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mempalace-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: mempalace-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: MEMPALACE_MCP_HTTP_TOKEN
      remoteRef:
        key: 9cc7a05a-1f3d-44df-8cbc-b48a0057df70
        property: password
    - secretKey: MEMPALACE_QDRANT_API_KEY
      remoteRef:
        key: 1eb3bf3e-805c-4134-a0e8-b48a005a9f22
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qdrant-api-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: qdrant-api-key
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: api-key
      remoteRef:
        key: 1eb3bf3e-805c-4134-a0e8-b48a005a9f22
        property: password
