---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mempalace
resources:
  - namespace.yaml
  - external-secrets.yaml
  - qdrant.yaml
  - mempalace.yaml
  - network-policy.yaml
configMapGenerator:
  - name: mempalace-python-dependencies
    files:
      - requirements.txt
