---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClass: true
      defaultFsType: ext4
      defaultClassReplicaCount: 2
    defaultSettings:
      defaultReplicaCount: 2
      defaultDataLocality: best-effort
      replicaSoftAntiAffinity: false
      storageMinimalAvailablePercentage: 10
      defaultLonghornStaticStorageClass: longhorn
      autoDeletePodWhenVolumeDetachedUnexpectedly: true
    ingress:
      enabled: true
      ingressClassName: traefik
      host: longhorn.k8s.${SECRET_DOMAIN}
      path: /
      tls: true
      tlsSecret: longhorn.local-tls
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        hajimari.io/enable: "true"
        hajimari.io/icon: "cow"
        hajimari.io/group: "storage"
        hajimari.io/appName: "longhorn"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
