---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atuin-config
  namespace: default
  labels:
    app.kubernetes.io/name: atuin
    app.kubernetes.io/instance: atuin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
