---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-login
spec:
  conditions:
    - namespaceSelector:
        matchLabels:
          external-secrets.io/bitwarden-access: "true"
  provider:
    webhook:
      url: http://bitwarden-cli.external-secrets.svc.cluster.local:8087/object/item/{{ .remoteRef.key }}
      headers:
        Content-Type: application/json
      result:
        jsonPath: $.data.login.{{ .remoteRef.property }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-fields
spec:
  conditions:
    - namespaceSelector:
        matchLabels:
          external-secrets.io/bitwarden-access: "true"
  provider:
    webhook:
      url: http://bitwarden-cli.external-secrets.svc.cluster.local:8087/object/item/{{ .remoteRef.key }}
      result:
        jsonPath: $.data.fields[?@.name=="{{ .remoteRef.property }}"].value
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-notes
spec:
  conditions:
    - namespaceSelector:
        matchLabels:
          external-secrets.io/bitwarden-access: "true"
  provider:
    webhook:
      url: http://bitwarden-cli.external-secrets.svc.cluster.local:8087/object/item/{{ .remoteRef.key }}
      result:
        jsonPath: $.data.notes
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-attachments
spec:
  conditions:
    - namespaceSelector:
        matchLabels:
          external-secrets.io/bitwarden-access: "true"
  provider:
    webhook:
      url: http://bitwarden-cli.external-secrets.svc.cluster.local:8087/object/attachment/{{ .remoteRef.property }}?itemid={{ .remoteRef.key }}
      result: {}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-ssh
spec:
  conditions:
    - namespaceSelector:
        matchLabels:
          external-secrets.io/bitwarden-access: "true"
  provider:
    webhook:
      url: http://bitwarden-cli.external-secrets.svc.cluster.local:8087/object/item/{{ .remoteRef.key }}
      headers:
        Content-Type: application/json
      result:
        jsonPath: $.data.sshKey.{{ .remoteRef.property }}
