# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:/DdAsyduFWRomAcnLLn7ipDCbI/9GHOL3rSkizjjVCu8gBfBew==,iv:an3pSKW9Tn0F0udMgpB4C6c4ZHXwtH2CxCefI6gB2dI=,tag:UpbV9ydt9+3FFBMW63RacA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vs9crdp7cxwjtlqu5l83a3pgdah9eau3afrhx7qyzkhag7avq0spf6rxp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRk1Jb2gwQ3pmZ3VQWGY0
            eDY4MjFqbmZkcCtjNVZydC9iYk1pUkV3ZVVRCjB3bEFlak81bU45S21tRkZwMGJ3
            YXV0U2ErWjBScUt1Mm5GVmRwbUtPbXcKLS0tIFkwR0FiR1U2REhrYzdwazQrOHBC
            SENqRWZUazZGR09rc2cwUXI3YUh6dFEKcYSZdUwQ2FiSeb77XC3UbxMax6aLDi8X
            +tBNdp6E3uReYHuybWjrMZmzPyGrwQdPSPmrxPXhN8Iqg9IEFNa7/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-02T04:52:39Z"
    mac: ENC[AES256_GCM,data:+5YMzfc/UDwwSqaKxbpqwAzhywyY6jiRO4XhbMoMou9HKSEAWymWwWJ3lF9jiB5Yp4Mad+5M5sO/Fesm1sNDFxAKWahbAXO8p9c9fnRcoyhnT7ujYGVCobHotc33FXEkRM0AO6fukpP+u+fCa4NZ7+ELp/vBIJNVLaO9R3s30TY=,iv:zfl+nPjSWaYPxj8bbYI+8kBpA5OXEadV1YmjJ2bxtQw=,tag:l671CaB3Ir2m0YelsBrBXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
