---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent-recovery
  namespace: system-upgrade
spec:
  serviceAccountName: system-upgrade
  concurrency: 1
  exclusive: true
  jobActiveDeadlineSecs: 10800
  version: v1.32.13+k3s1
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
      - key: kubernetes.io/hostname
        operator: In
        values:
          - n4l.k8s.lazy.sh
  drain:
    ignoreDaemonSets: true
    deleteEmptydirData: true
    force: false
    disableEviction: false
    timeout: "2h"
  upgrade:
    image: rancher/k3s-upgrade
