apiVersion: v1
kind: Secret
metadata:
    name: unpoller-secret
    namespace: observability
stringData:
    UP_UNIFI_DEFAULT_API_KEY: ENC[AES256_GCM,data:2A3hC87u93hfqN6aE1n/VIiXGLihv2LRoZ6EwXTHuMk=,iv:RzemK9EF9DPoWVL41P7gcXnjkb6ebQ/K7LDv5lx/lZk=,tag:i5EBaqsRGizDCzD9f0aEsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySG9PUVBiZFM3Z0RWMjJa
            WFVTZjliM3h3eU93b1BaZnA4UjRDY0ZvQm1NCkNKKzgwRVFrVlNQZ1dIWU40OW1P
            cDY2dGNiV0VMejMwaTY1aGo1REVoQ2cKLS0tIHgxb0NUL0lLVlFJRE9uM1BNMmZw
            Q0MzRWVqTFJsZjNER1c5QzJUS2dGOTgK0aXvJAnCZH3KklFVU9CBHOrIjnVto+1F
            ua6yON6sFsZSS5tHMP7Kl9abH7Vus7sMBCS7Wiu557FqBgLXVzFCTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16vs9crdp7cxwjtlqu5l83a3pgdah9eau3afrhx7qyzkhag7avq0spf6rxp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-15T05:13:27Z"
    mac: ENC[AES256_GCM,data:2wYLzGrLp/teN7bLkG0Zp0PSWi7+5bSu0mBe16NOcRwK/JXGHtub9ZgvgG4RiQQ9EpKjLVX7nU1o02D0ve5LHVN5g5HKw7gM7YY0XqrPs9DIOiG8RRo/WqPXP3bixWBlzSMYWBNYc1NiV6F7yb8W1EJePtdHzWil1Yfz5lZkip8=,iv:bYFKt2VpoN5rDyMw5Q3UHJA53/QZ3c9r+cFi/atoE60=,tag:6v1//8ekkb0GdJtnELpBIQ==,type:str]
    version: 3.13.0
